stages:
  preprocess:
    cmd: |
      poetry run python src/data/preprocess_air_data.py
      git commit -am "Updated preprocessed air data on $(date) with DVC pipeline and GitHub workflows" || true
      git push || true
      dvc push || true
    deps:
    - src/data/preprocess_air_data.py
    - data/raw/air/air_data.xml
    params:
    - preprocess.station
    outs:
    - data/preprocessed/air:
        persist: true

  validate:
    cmd: |
      cd gx && poetry run python run_checkpoint.py
    deps:
    - data/preprocessed/air/
    outs:
    - gx/uncommitted:
        persist: true

  test_data:
    cmd: |
      poetry run python src/data/test_data.py
    deps:
    - data/preprocessed/air/
    - src/data/test_data.py
    outs:
    - data/reference/air:
        persist: true

  train:
    cmd: |
      poetry run python src/model/train.py
      git commit -am "Updated models on $(date) with DVC pipeline and GitHub workflows" || true
      git push || true
      dvc push || true
    deps:
    - src/model/preprocess.py
    - src/model/train.py
    - data/preprocessed/air/
    - gx/uncommitted
    - data/reference/air
    params:
    - train.test_size
    - train.random_state
    - train.window_size
    - train.target_col
    outs:
    - models/:
        persist: true
