name: Fetch data on schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes

jobs:
  fetch_air:
    name: Fetch and pre-process air data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3

      - name: Add Poetry to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run fetch script
        run: poetry run python src/data/fetch_air_data.py

      - name: Run preprocess script
        run: poetry run python src/data/preprocess_air_data.py

      - name: Commit data changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data || echo "No changes to commit"
          git commit -m "🔄 Updated air data on $(date '+%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"
          git push
